### ISSUE TITLE
takeE/dropE

### ISSUE THREAD

**Issue by TobBrandt** [HeinrichApfelmus/reactive-banana#100]
I'd like to have the two functions

    takeE :: Int -> Event t a -> Event t a
    dropE :: Int -> Event t a -> Event t a

with the obvious behaviour.

I implemented them myself, but I guess they could be implemented more efficiently with access to the internals of reactive banana.

    -- tag each event occurrence with its index, starting with 0
    tagE :: Event t a -> Event t (Int, a)
    tagE e = accumE (-1, error "this is a bug") (fmap next e)
        where
            next val (acc, _) = (acc + 1, val)

    takeE :: Int -> Event t a -> Event t a
    takeE n e = fmap snd $ filterE (\(i, _) -> i < n) $ tagE e

    dropE :: Int -> Event t a -> Event t a
    dropE n e = fmap snd $ filterE (\(i, _) -> i >= n) $ tagE e

The suffer multiple problems

1. The tag could overflow. If `Int` is 32bit and you produce events once every ms, it takes about a month to overflow. Not a big issue, but could happen in a long running process. On 64bit it's pratically impossible.
2. `takeE` has to keep handling the event even after `n` occurrences, because the fact that `filterE` will filter out all future values is only known to us.
3. `dropE` has to keep adding up integers for similar reasons.

2 and 3 have knock-on effects, because they keep subscribed event handlers downstream in memory that could potentially be garbage collected.

Is it possible to improve upon the above implementation?

**Comment by HeinrichApfelmus** [comment]
These combinators are very specialized, so I'm not sure if I want include them in the `Reactive.Banana.Combinators` module. Maybe in a separate module, though. Could you tell me in which context you needed these combinators?

For 2 and 3, you can use dynamic event switching, in particular `switchE`, to drop the input event stream altogether.

**Comment by TobBrandt** [comment]
I don't have any particular use in mind, but these are common functions in other reactive libraries. For example in .NET there is [Observable.Take](https://msdn.microsoft.com/en-us/library/hh229852(v=vs.103).aspx) and [Observable.Skip](https://msdn.microsoft.com/en-us/library/hh229847(v=vs.103).aspx). Basically, anything you can do with lists in a streaming fashion should also be possible with events.

I tried implementing the functions using `switchE`, but I didn't get very far. I don't think I understand the `Switch` module yet.

**Comment by the-real-blackh** [comment]
My view on this is that systems like Reactive Extensions have 'take' and 'drop' because they are attempting to provide functional list-like operations to languages that lack them. "True" FRP systems (i.e. FRP according to Conal Elliott's definition) are tied to a global time-base, so take and drop don't make sense as common operations. In Rx terminology they are concerned only with "hot observables". There may be a need for them in specific cases, but I don't think they belong in the library.

**Comment by HeinrichApfelmus** [comment]
Thanks for the context, Steven! In this light, I'm going to close the issue and not add the combinators, until a concrete use case comes up.
