### ISSUE TITLE
Register for Stackage

### ISSUE THREAD

**Issue by sgraf812** [HeinrichApfelmus/reactive-banana#102]
I just submitted a [PR](https://github.com/fpco/stackage/pull/755) for submission to Stackage for this library, threepenny-gui and operational. I hope you are fine with that!

**Comment by HeinrichApfelmus** [comment]
As mentioned in the other discussion, I'm currently unable to be responsive enough for the [stackage maintainers agreement](https://github.com/fpco/stackage/wiki/Maintainers-Agreement). I'm afraid this means to inclusion into stackage for the time being.

**Comment by Anrock** [comment]
@HeinrichApfelmus hello, is there any updates for this issue?

**Comment by HeinrichApfelmus** [comment]
@ocharles ?

**Comment by ocharles** [comment]
Sorry, been slacking on this! On holiday atm but will try and address this
next week

**Comment by ocharles** [comment]
Ok, I've sent the request: https://github.com/fpco/stackage/pull/2471

**Comment by ocharles** [comment]
All done! @HeinrichApfelmus should I have access to close issues here? If not, this can be closed :)

**Comment by HeinrichApfelmus** [comment]
Great, thanks! 👍
