### ISSUE TITLE
Monadic API: Confusion with observeE

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#105]
Take the following program:

```haskell
import Control.Monad
import Reactive.Banana hiding (accumB)
import Reactive.Banana.Frameworks
import Control.Concurrent (forkIO)

main :: IO ()
main =
  do (keyPressAh,fireKeyPress) <- newAddHandler
     (clockAh,tickClock) <- newAddHandler
     network <-
       compile (do keyPress <- fromAddHandler keyPressAh
                   clock <- fromAddHandler clockAh
                   let n =
                         switchB (pure 0)
                                 (observeE (fmap (const (integrate clock 0 (pure 1))) keyPress))
                   reactimate (print <$> n <@ clock))
     actuate network
     forkIO (forever (tickClock 1))
     forever (getChar >>= fireKeyPress)
  where integrate dt initial x =
          accumB initial ((+) <$> ((*) <$> x <@> (dt :: Event Double)))
        accumB initial e =
          stepper initial =<< accumE initial e
```

Is this program we have a clock pulse that fires repeatedly. When the user presses a key, the local clock gets reset and we start counting from 0.

However, the above program only allows the user to reset the clock once. When a key is pressed the local clock begins increasing, but repeated key presses have no effect. The expectation would be that subsequent key presses reset the clock to 0 and begin increasing again.

**Comment by ocharles** [comment]
Test case added in https://github.com/HeinrichApfelmus/reactive-banana/commit/d18251c1d4cf2a76ecfa37ab0fa6c198b50727e3

**Comment by HeinrichApfelmus** [comment]
Ouch, that's an embarrassing bug. :sweat_smile: I have (hopefully) fixed the implementation, but the model needs a complete rewrite, so the test case will still fail at the moment.

**Comment by ocharles** [comment]
Yep, works perfectly now - thanks!

**Comment by HeinrichApfelmus** [comment]
Test suite succeeds as of ff0b914b8812f22ed7e03adecea2db0bc173e707 . Feel free to open new issues if you meet more bugs. :smile:
