### ISSUE TITLE
Change `accumB/E` to accept a list of events?

### ISSUE THREAD

**Issue by HeinrichApfelmus** [HeinrichApfelmus/reactive-banana#106]
The most common way to use the `accumB/E` functions is to apply it to an event that was built as a union of several different events:

    let unions = foldr1 $ unionWith (.)
    in accumB x $ unions [e1, e2, e3]

I wonder if it's a good idea to bake this right into the combinators, changing their types to

    accumB :: MonadMoment m => a -> [Event (a -> a)] -> m (Behavior a)
    accumE :: MonadMoment m => a -> [Event (a -> a)] -> m (Event a)

With these types, a snippet in the Asteroids.hs example would read

    -- ship position
    (bship :: Behavior Int)
        <- accumB (width `div` 2)
            [ goLeft  <$ eleft
            , goRight <$ eright
            ]
    let
        goLeft  x = max 0          (x - 5)
        goRight x = min (width-30) (x + 5)

What do you think?

The alternative would be to at least export the convenience function

    unions ;: [Event (a -> a)] -> Event (a -> a)
    unions [] = never
    unions xs = foldr1 (unionWith (.)) xs

or to implement an instance

    instance Monoid (Event (a -> a))

as discussed in issues #50 and #104. (That would essentially be the instance `Moment (Event (Endo a)))`, but the additional `Endo` newtype introduces notational overhead. in the example code taken from Asteroids.hs, the `goLeft` and `goRight` functions would have to be converted to `Endo`.)

**Comment by ocharles** [comment]
I am using `unionWith` with different functions in a little platformer I'm building at the moment:

```haskell
        in accumB (V2 0 0)
                  (unionWith (.)
                             (fmap (over _x)
                                   (liftA3 adjustHorizontalSpeed
                                           currentBearing
                                           controllerBearing
                                           onTheFloor <@>
                                    stepPhysics))
                             (fmap (over _y)
                                   (unionWith const
                                              (const initialJumpSpeed <$
                                               (whenE onTheFloor
                                                      (filterE (Pressed ==)
                                                               (keyMotion ScancodeSpace sdlEvent))))
                                              (adjustVerticalSpeed <$>
                                               tagKey ScancodeSpace True False <@>
                                               stepPhysics))))
```

That said, the top level combinator is `(.)` again, so this would work.

I do think that changing `accumB` and `accumE` is a bit too opinionated, however. `unions` seems like the right kind of approach. Note that if you have `Monoid a => Monoid (Event a)` then you can do:

```haskell
accumB initial (ala Endo foldMap [ goLeft <$ eLeft, goRight <$ eRight ])
```

which I think removes the notational overhead you mention with `Endo`.

**Comment by HeinrichApfelmus** [comment]
> I do think that changing accumB and accumE is a bit too opinionated, however. unions seems like the right kind of approach. 

Agreed. I have added the `unions` combinator and updated all examples in `reactive-banana-wx`.
