### ISSUE TITLE
Garbage collection happens too early with GHCJS

### ISSUE THREAD

**Issue by HeinrichApfelmus** [HeinrichApfelmus/reactive-banana#109]
Currently, GHCJS [deviates from the official semantics for weak pointers][1]. Unfortunately, this means that even simple programs that use reactive-banana will not work when compiled with GHCJS.

The [`ghcjs` branch][2] contains an experimental workaround. I currently don't have GHCJS installed, so I have to rely on your feedback. Does commit 211e221435514bd055a2494dc8e61a004445a299 help?

  [1]: https://www.reddit.com/r/haskell/comments/3ly4pe/which_frontend_library_to_use_with_ghcjs/cvbrc34
  [2]: https://github.com/HeinrichApfelmus/reactive-banana/tree/ghcjs

**Comment by HeinrichApfelmus** [comment]
Any luck with commit 5a536835111bc74f026346076dac59a2e7994e77 ?

**Comment by luite** [comment]
I've implemented the semantics to follow those of GHC more accurately, and I've added some tests to the GHCJS testsuite. Do you have a simple (non-interactive, runs in terminal with `node.js`) example that shows different behaviour with GHCJS? Ideal would be a testcase with thinks like `threadDelay` and `forkIO` that prints some results to stdout.

**Comment by HeinrichApfelmus** [comment]
The following example (using the 1.0 API) by Oliver Charles will print consecutive numbers until garbage collection happens, then it will print the same number over and over. It runs in the main thread.

    import Reactive.Banana
    import Reactive.Banana.Frameworks

    main :: IO ()
    main = do
        (ah,tick) <- newAddHandler
        network   <- compile $ do
            etick <- fromAddHandler ah
            e     <- accumE 0 (succ <$ etick)
            reactimate $ print <$> e
        actuate network
        mapM_ tick [1..]

Is this what you are looking for?

**Comment by luite** [comment]
Yes. So this example used to give problems?

It appears to do the correct thing with GHCJS master, with `reactive-banana` compiled from the master branch.

**Comment by HeinrichApfelmus** [comment]
This program used to give problems, indeed. Assuming that garbage collection has happened in your tests, and the program still prints a list of consecutive numbers (instead of always the same number), then it looks like everything is working now.

Thanks Luite!

**Comment by luite** [comment]
Yep, I tested with `-DGHCJS_TRACE_GC` to verify that GC was indeed happening.

There's a test in the testsuite now to verify the basic weak ref semantics: `rts/weak/weak001.hs`, but test coverage could still be better. Please report any remaining programs where GHCJS doesn't appear to behave correctly, if you find them. Thanks!

**Comment by HeinrichApfelmus** [comment]
Awesome! I'll report anything that comes up. Thanks again!
