### ISSUE TITLE
add `mapIO' :: (a -> IO b) -> Event a -> MomentIO (Event b)

### ISSUE THREAD

**Issue by eallik** [HeinrichApfelmus/reactive-banana#110]
I'm converting the SO comment to an issue, verbatim, as a reminder as you requested.

> wouldn't it make sense to include mapIO in reactive-banana? IO seems like a big deal, and the more of the boilerplate for it that has been taken care of by reactive-banana, and that is otherwise hard to get right and easy to get wrong, given the tricky relationship between FRP and IO, the easier it is to build real life apps with the library. For example, it's likely I'd have found about everything you said in a trial and error manner, after my FRP app started misbehaving because I was using execute with slow IO.

**Comment by HeinrichApfelmus** [comment]
Thanks! Implemented.

**Comment by ocharles** [comment]
I'm curious, what does this combinator do that `execute`, `liftIO` and `fmap` don't do?

**Comment by ocharles** [comment]
Ok, https://stackoverflow.com/questions/32916738/reactive-banana-consume-parametrized-call-to-an-external-api seems to discuss this, but I don't entirely understand the difference. There is some mention of "expensive" computations, but I don't understand why using `reactimate` and pushing into a new event would solve that - `reactimate`s are still executed synchronously, so it still blocks the whole process - no?

**Comment by HeinrichApfelmus** [comment]
@ocharles There are two differences:

1. As you've already found out, `mapIO` is guaranteed to execute the IO action, while `execute` is more of a helper function that allows you to perform a little IO when absolutely necessary.

2. The Event returned by `execute` is simultaneous with the argument Event, while the Event returned by `mapIO` may happen much later.

    A consequence of this is that If the argument of `execute` blocks, then the whole EventNetwork is blocked as well. This is necessary to ensure simultaneity.

    On the other hand, `reactimate` will always happen after all Behaviors have been updated and the network is ready to process another event. If one `reactimate` blocks, then all the other `reactimates` that were scheduled for this Moment will also block, but the EventNetwork will still accept new inputs from other threads and proceed normally.

**Comment by ocharles** [comment]
Ah, I hadn't considered that other friends could push data into the network. That makes a lot more sense, thanks! Maybe we should think about adding that information into the documentation? It's certainly there in pieces at the moment (`reactimate` hints that it doesn't block), but it's hard to get to your answer just from the Haddocks. I'm not entirely sure what I'd write, but maybe mentioning that `execute` blocks and `reactimate` doesn't is enough. `execute` could even point to `mapIO` to avoid the anti-pattern of doing heavy IO in `execute`, as I suggested in my first comment.
