### ISSUE TITLE
Has Reactive Banana anything to do with catamorphisms?

### ISSUE THREAD

**Issue by danse** [HeinrichApfelmus/reactive-banana#113]
I am wondering, given the name, whether is there any relationship. It might help understanding the theoretical foundations

**Comment by HeinrichApfelmus** [comment]
No. The reactive-banana library has absolutely nothing to do with the "bananas, lenses and barbed wires" that are sometimes used as imaginative descriptions for a certain mathematical notation that is used in the context of generalized folds.

The library does rely on some concepts that have a nice description in terms of category theory, in this case Monad, Applicative Functor and Monoid, but the generalized folds / F-algebras are not used here.
