### ISSUE TITLE
Can't install wxHaskell on Ubuntu 12.04 — possible alternatives?

### ISSUE THREAD

**Issue by Wizek** [HeinrichApfelmus/reactive-banana#115]
Hello,

I've tried to

```
cabal get reactive-banana-wx-1.0.0.0
cd reactive-banana-wx-1.0.0.0
cabal sandbox init
cabal install
```

and soon found out that that won't work without libwxgtk3.0-dev, which is not available in the package repository for Ubuntu 12.04.

I've tried many different paths, all of which are a dead-end so far:

#### 1) Install `libwxgtk3.0-dev` via PPA

Following these instructions: http://codelite.org/LiteEditor/WxWidgets30Binaries#toc2
Which resulted in this error down the path: https://gist.github.com/Wizek/32da80b593efaf0c4529
More details: http://stackoverflow.com/questions/33427435/how-can-i-verify-if-wxwidgets-3-0-2-is-installed-correctly

#### 2) try to compile wxWidgets 3.0.2 from source

Running `configure` told me that I was missing gtk: https://gist.github.com/Wizek/526e261d8873ca61462a

Trying to install those, however, `apt-get` refused to do so for some reason:

- v3: https://gist.github.com/Wizek/7b5d846319bf898d2e82
- v2: https://gist.github.com/Wizek/ee3ee6c07e5dd1355e9c 

#### 3) try to use wxWidgets 2.8 instead

At this point I was asking myself: "Do I even need wxWidgets 3.0? Wouldn't 2.8 suffice for now?"

Trying to

```
cabal install -fbuildExamples -j --constraint={wxcore,wxc,wx,wxdirect}" <0.14" --constraint="cabal ==1.20.*" --allow-newer=array
```
lead me to this error:

```
➜  reactive-banana-wx-1.0.0.0 git:(master) ✗ cabal install -fbuildExamples -j --constraint={wxcore,wxc,wx,wxdirect}" <0.14" --constraint="cabal ==1.20.*" --allow-newer=array
Resolving dependencies...
Notice: installing into a sandbox located at
/home/wizek/sandbox/exp-frp/reactive-banana-wx-1.0.0.0/.cabal-sandbox
Configuring reactive-banana-wx-1.0.0.0...
Building reactive-banana-wx-1.0.0.0...
Failed to install reactive-banana-wx-1.0.0.0
Build log ( /home/wizek/sandbox/exp-frp/reactive-banana-wx-1.0.0.0/.cabal-sandbox/logs/reactive-banana-wx-1.0.0.0.log ):
Configuring reactive-banana-wx-1.0.0.0...
Building reactive-banana-wx-1.0.0.0...
Preprocessing library reactive-banana-wx-1.0.0.0...
In-place registering reactive-banana-wx-1.0.0.0...
Preprocessing executable 'Animation' for reactive-banana-wx-1.0.0.0...
Linking dist/dist-sandbox-d056b5d0/build/Animation/Animation ...
/usr/bin/ld: /home/wizek/sandbox/exp-frp/reactive-banana-wx-1.0.0.0/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.4/wxcore-0.13.2.3/libHSwxcore-0.13.2.3.a(eljframe.o): undefined reference to symbol '__cxa_guard_abort@@CXXABI_1.3'
/usr/bin/ld: note: '__cxa_guard_abort@@CXXABI_1.3' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.6/libstdc++.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6/libstdc++.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
cabal: Error: some packages failed to install:
reactive-banana-wx-1.0.0.0 failed during the building phase. The exception
was:
ExitFailure 1
```

### Questions

Is what I am trying to do even possible? And if so, do you have any pointers on what I could try to get reactive-banana working on my machine?

**Comment by HeinrichApfelmus** [comment]
I'm afraid, but the problem you are experiencing is not related to `reactive-banana-wx` directly. Instead, I have to refer you to the [wxHaskell][1] project. That said, perhaps the combination WxWidgets 2.9 and `wx >= 0.90` could work for you. I don't use Linux, so I can't help with that.

If you want to try out FRP without installation headache, perhaps my [Threepenny-GUI library][2] may be a suitable alternative. (It doesn't use reactive-banana, yet, but the API is very similar.)

  [1]: https://github.com/wxHaskell/wxHaskell
  [2]: https://wiki.haskell.org/Threepenny-gui

**Comment by Wizek** [comment]
Thanks for mentioning Threepenny-GUI, I haven't heard about it yet, and was indeed frustrated with the difficulty of installing RB with wx. I'll be giving threepenny a try so I can at least get some more hands-on experience with FRP.

Btw, I also read somewhere that RB can work with different backends, other than wx. Is that true? Could I perhaps install/use it with something other than wx, e.g. gtk directly, somehow? Or somehow else that might be easier to install?

**Comment by HeinrichApfelmus** [comment]
> Btw, I also read somewhere that RB can work with different backends, other than wx. Is that true? Could I perhaps install/use it with something other than wx, e.g. gtk directly, somehow?

Yes, other people have written bindings to GTK, for instance [reactive-banana-gtk][1]. Could be easier on Linux, but as said, I can't know, because I'm on OS X.

  [1]: https://github.com/ocharles/reactive-banana-gtk
