### ISSUE TITLE
Hackage docs not available for 1.1.0.0

### ISSUE THREAD

**Issue by eallik** [HeinrichApfelmus/reactive-banana#123]
The URL http://hackage.haskell.org/package/reactive-banana-1.1.0.0/docs/Reactive-Banana-Frameworks.html#v:fromAddHandler responds with:

> There is no documentation for reactive-banana-1.1.0.0. See https://hackage.haskell.org/package/reactive-banana/docs/Reactive-Banana-Frameworks.html for the latest version.

**Comment by jdreaver** [comment]
Hackage takes some time to build the docs. At the bottom of the Properties section of [this page](http://hackage.haskell.org/package/reactive-banana), you can see that the Status field says "Docs Pending".

**Comment by eallik** [comment]
Are the docs still not supposed to be there 16 hours later?

**Comment by HeinrichApfelmus** [comment]
Hackage often needs a couple of days to build documentation, there is nothing I can do about that.

What I can do is build and upload the documentation by hand. I did that just now, but it appears that sources didn't get hyperlinked correctly, which is a pity for `Reactive.Banana.Model`. I can't seem to undo this. Oh well.

**Comment by eallik** [comment]
Is building the docs such an expensive operation then?
On Wed, 6 Jan 2016 at 16:11, Heinrich Apfelmus <notifications@github.com>
wrote:

> Hackage often needs a couple of days to build documentation, there is
> nothing I can do about that.
>
> What I can do is build and upload the documentation by hand. I did that
> just now, but it appears that sources didn't get hyperlinked correctly,
> which is a pity for Reactive.Banana.Model. I can't seem to undo this. Oh
> well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HeinrichApfelmus/reactive-banana/issues/123#issuecomment-169332065>
> .
>
-- 
Best Regards,
Erik Allik

**Comment by jdreaver** [comment]
> Is building the docs such an expensive operation then?

You basically need to build the package in its entirety, including all dependencies, so it can indeed be very expensive. I imagine the main bottleneck for Hackage is the large number of packages. If each package takes 10 minutes to build, then 100 package updates can fill up the doc building queue for the better part of a day.

**Comment by eallik** [comment]
I guess it doesn't do it incrementally, so that only the differences from
the previous version are built.
On Wed, 6 Jan 2016 at 16:38, John David Reaver <notifications@github.com>
wrote:

> Is building the docs such an expensive operation then?
>
> You basically need to build the package in its entirety, including all
> dependencies, so it can indeed be very expensive. I imagine the main
> bottleneck for Hackage is the large number of packages. If each package
> takes 10 minutes to build, then 100 package updates can fill up the doc
> building queue for the better part of a day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HeinrichApfelmus/reactive-banana/issues/123#issuecomment-169339469>
> .
>
-- 
Best Regards,
Erik Allik

**Comment by ocharles** [comment]
How are you building your own docs? I recommend the 'neil' binary which has
a command to build & upload documentation - ive never seen it do the wrong
thing. It's on Hackage.

**Comment by HeinrichApfelmus** [comment]
@ocharles  Thanks for the `neil` tip! I had used a script by Edward Kmett to build the docs.

**Comment by ocharles** [comment]
I think this can be closed now.
