### ISSUE TITLE
adapt to GHC-8.0.1

### ISSUE THREAD

**Issue by amigalemming** [HeinrichApfelmus/reactive-banana#124]
Using `ghc-8.0.0.20160109` I get:
~~~~
Preprocessing library reactive-banana-1.1.0.0...
[ 1 of 22] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/Reactive/Banana/Prim/Util.o )

src/Reactive/Banana/Prim/Util.hs:54:25: error:
    • Couldn't match expected type ‘GHC.State# GHC.RealWorld
                                    -> (# GHC.State# GHC.RealWorld, c0 #)’
                  with actual type ‘IO ()’
    • In the third argument of ‘GHC.mkWeak#’, namely ‘f’
      In the expression: GHC.mkWeak# r# v f s
      In the expression:
        case GHC.mkWeak# r# v f s of {
          (# s1, w #) -> (# s1, GHC.Weak w #) }
Failed to install reactive-banana-1.1.0.0
~~~~

**Comment by HeinrichApfelmus** [comment]
The purpose of the affected function, [`mkWeakIORefValueFinalizer`][1], is to create a weak pointer to an IORef that actually works. In older versions of GHC, using GHC internals was necessary to achieve this. I have no idea how it works in GHC 8, it could be that there is a corresponding library function that works correctly.

  [1]: https://github.com/HeinrichApfelmus/reactive-banana/blob/master/reactive-banana/src/Reactive/Banana/Prim/Util.hs#L49

**Comment by atzeus** [comment]
There is a special method in Data.IORef: mkWeakIORef. This does the right
thing in my experience.
