### ISSUE TITLE
Suggestion: function to map successive values of an Event into another Event

### ISSUE THREAD

**Issue by jdreaver** [HeinrichApfelmus/reactive-banana#127]
Hello! I recently needed to compare successive values of an `Event a` to produce a new `Event b`. Here is what I came up with:

```haskell
-- | Map a function to successive values of an event stream to produce a new
-- event.
mapSuccE :: (a -> a -> b) -> a -> Event a -> Moment (Event b)
mapSuccE f x0 event =
  do pairs <- accumE (x0, x0) $ (\e' (_, e) -> (e, e')) <$> event
     return $ uncurry f <$> pairs
```

A simplified version of my use case was to produce an `Event Bool` signifying that another event changed from `Nothing` to `Just a`:

```haskell
changedToJust :: Event (Maybe a) -> Moment (Event Bool)
changedToJust maybeE = mapSuccE f Nothing maybeE
  where f x1 x2 = isNothing x1 && isJust x2
```

Is this a useful function to have predefined in `reactive-banana`? I just thought I would suggest it here and show my implementation in case anyone else found it useful.

**Comment by HeinrichApfelmus** [comment]
I'm not sure, this function seems a bit too specialized for my taste. I would simply use a Behavior to keep track of the previous state. Then, the `changedToJust` function can be written as

```haskell
changedToJust maybeE = do
        b <- stepper Nothing maybeE
        return $ f <$> b <@> maybeE
    where
    f x1 x2 = isNothing x1 && isJust x2

**Comment by jdreaver** [comment]
Ah, that's probably correct.

One thing I was struggling with in FRP is knowing how to perform small computations like this. I understand all of the primitive functions in reactive-banana, and I usually can sense something like this is possible before I implement it, but piecing the functions together takes some experience. 

When I have more time, I will consider writing up a list of the utility functions I use like this and either put them on my blog or make a pull request to your [frp-guides](https://github.com/HeinrichApfelmus/frp-guides), so at least the ability for people to Google common FRP tasks goes up.

Thanks!

**Comment by HeinrichApfelmus** [comment]
Sure! My usual approach to these kind of problems is to define a Behavior for every piece of state that I need and then use the applicative combinators and `<@>` to define new events.

**Comment by HeinrichApfelmus** [comment]
Closing. Please don't hesitate to reopen if necessary.
