### ISSUE TITLE
Include stack.yaml?

### ISSUE THREAD

**Issue by Wizek** [HeinrichApfelmus/reactive-banana#129]
I've recently built `reactive-banana-wx` with stack, and ended up with this stack.yaml file:

https://gist.github.com/Wizek/7fc41b446f439d9a9223#file-stack-yaml

Would you be willing to include this or something similar? It might save some time for others.

**Comment by HeinrichApfelmus** [comment]
Sure, why not.

**Comment by HeinrichApfelmus** [comment]
The stack.yml file is in the source repository, but not included in the package on Hackage. Let me know if the latter should be improved.
