### ISSUE TITLE
dynamic elements of a panel

### ISSUE THREAD

**Issue by archaephyrryx** [HeinrichApfelmus/reactive-banana#130]
Hello,

I have been working on trying to migrate a number of widgets I had written for threepenny-gui applications over to reactive-banana, and have gotten things to the point where I can more or less muddle through on things, except for low-level side-effects that I don't know how to avoid or account for. (my project link is https://github.com/archaephyrryx/CCG-Project/tree/reactive-banana/Widgets). 

I am going to try to simplify the circumstances as much as possible, to sidestep irrelevant details and also get to the root of the problem more quickly. What I am trying to do is create a widget that acts as a lens on a list of values, displaying a certain range of values at any given time (where the values themselves are represented by button widgets that carry the index they correspond to), with the sublist chosen based on a `Behavior Int` determining how many I am showing, and a `Behavior Int` determining which chunk of that size I am showing. The problem is, when I try to `sink` on the `layout` attribute of the `Panel ()` I am holding all these rendered (but possibly undisplayed) buttons in by the generated `Behavior [Button ()]`, there is an artifact whereby all of the `Button ()` in the list are rendered, stacked on top of one another, as if they were all simultaneously selected as the chunk to display. I suspect the reason is that the items which have not been specified in the layout have a default location, or something to do with not calling a function on each event that triggers the frame shift, but I don't exactly know what the true problem is or how to fix it. `reactimate` and `refit` seem like they might be in the right neighborhood.

Here is a minimalized mockup that spaces things out so the artifacts don't just stack into a black spot.

```haskell
{-# LANGUAGE RecursiveDo #-}

import Reactive.Banana
import Reactive.Banana.Frameworks
import Reactive.Banana.Combinators
import Reactive.Banana.WX
import Graphics.UI.WX
import Graphics.UI.WXCore

main :: IO ()
main = start test

test :: IO ()
test = do
    f <- frame [text := "Test"]

    add <- button f [ text := "+" ]
    next <- button f [ text := ">" ]
    prev <- button f [ text := "<" ]
    pos <- staticText f [ text := "0" ]

    let networkDescription :: MomentIO ()
        networkDescription = mdo
                eAdd  <- ((length <$> bItems) <@) <$> event0 add command
                ePrev <- event0 prev command
                eNext <- event0 next command

                bNext <- accumB 0 $ succ <$ eAdd
                reAdd <- mapEventIO (\n -> staticText f [ text := replicate n '\t' ++ show n ]) eAdd
                let eAll = flip (:) <$> bItems <@> reAdd
                bItems <- stepper [] eAll
                let eChange :: Reactive.Banana.Event (Int -> Int)
                    eChange = unions [whenE bNotFirst (pred <$ ePrev), whenE bNotLast (succ <$ eNext)]
                bCur <- accumB 0 eChange

                let bNotFirst = (>0) <$> bCur
                    bNotLast = (\x y -> x + 1 < y) <$> bCur <*> (length <$> bItems)
                    bThis = (\i xs -> if null xs then [] else [xs!!i]) <$> bCur <*> bItems

                sink pos [ text :== show <$> bCur ]
                sink f [ layout :== (grid 5 5 . ([widget add, widget prev, widget pos, widget next]:) . map (\x -> [widget x])) <$> bThis]
    network <- compile networkDescription
    actuate network
```

Can anyone provide insight?

**Comment by HeinrichApfelmus** [comment]
> [..] There is an artifact whereby all of the Button () in the list are rendered, stacked on top of one another, as if they were all simultaneously selected as the chunk to display.
> I suspect the reason is that the items which have not been specified in the layout have a default location, or something to do with not calling a function on each event that triggers the frame shift, but I don't exactly know what the true problem is or how to fix it.

I didn't have time to look at the example in detail, but I have encountered this problem at some point as well. This seems to be an issue with WxWidgets: If you remove a Widget from the layout, then it will be drawn at some default location. I think the right solution is to either 1) delete the Widget entirely or 2) use the hide/show/visibility properties of the widget. Maybe the latter approach can help with your case?

**Comment by archaephyrryx** [comment]
@HeinrichApfelmus 

Thanks for the suggestion! Don't worry about checking out my example, I am confident that that is the issue in question. I will see how visibility works.

**Comment by archaephyrryx** [comment]
@HeinrichApfelmus 

Just a quick update. Visibility seems to work, but creating a widget in IO context for mapEventIO, and mapping it later to a MomentIO context to sink its visibility is somewhat unwieldy a pattern. Is there any better way of doing this?

**Comment by HeinrichApfelmus** [comment]
> Creating a widget in IO context for mapEventIO, and mapping it later to a MomentIO context to sink its visibility is somewhat unwieldy a pattern. Is there any better way of doing this?

I'm a bit lost. Could you give an example of this pattern?

In general, I have intended `execute` to be appropriate for creating widgets on the fly, you don't have to use `mapEventIO` for that. Remember that you can use `liftIO` to lift IO actions into the MomentIO monad. See also the [BarTab example][1].

  [1]: https://github.com/HeinrichApfelmus/reactive-banana/blob/master/reactive-banana-wx/src/BarTab.hs#L40

**Comment by atzeus** [comment]
On a related note, does anyone know how to delete widgets in Wx? It seems a bit redundant to just put them on invisible.

**Comment by atzeus** [comment]
Answering my own question: https://hackage.haskell.org/package/wxcore-0.92.2.0/docs/Graphics-UI-WXCore-WxcTypes.html 

method objectDelete
