### ISSUE TITLE
Generalize `unionWith`

### ISSUE THREAD

**Issue by sgraf812** [HeinrichApfelmus/reactive-banana#138]
I'd love to have  `unionWith :: (a -> a -> a) -> Event a -> Event a -> Event a` generalized to `unionWith :: (a -> b -> c) -> Event a -> Event b -> Event c`.

**Comment by avieth** [comment]
This would have to be quite a different function. If `unionWith :: (a -> b -> c) -> Event a -> Event b -> Event c` then `unionWith f left right` can't always fire at the same time as `left` and `right`: if `left` fires before `right` then there's not enough information to come up with a value of type `c`.

What you're probably after is `unionWith f left right = f <$> left <*> right` if `Event` were an applicative. This event would fire whenever both events have fired at least once, using the latest value from each to come up with its combined value. Even though it's not applicative, you can make a weird mutation of `<*>`:

```Haskell
eventAp :: Event (a -> b) -> Event a -> Moment (Event b)
eventAp evF evX = do
  latestF <- stepper Nothing (Just <$> evF)
  latestX <- stepper Nothing (Just <$> evX)
  -- If evF and evX fire simultaneously, combine them
  let simultaneous = unionWith applyPartial (F <$> evF) (X <$> evX)
  let fromBoth = pickY <$> simultaneous
  -- When evF fires, apply it to the latest value from evX
  let fromF = (\maybex f -> pure f <*> maybex) <$> latestX <@> evF
  -- Similar for evX firing
  let fromX = (\maybef x -> maybef <*> pure x) <$> latestF <@> evX
  -- Now combine these three events in such a way that simultaneous
  -- occurrences are favoured
  let combined = unionWith const (filterJust fromBoth) (unionWith const (filterJust fromF) (filterJust fromX))

data Partial a b where
  F :: (a -> b) -> Partial a b
  X :: a -> Partial a b
  Y :: b -> Partial a b

applyPartial :: Partial a b -> Partial a b -> Partial a b
applyPartial (F f) (X x) = Y (f x)
applyPartial _ _ = error "Irresponsible use of Partial and applyPartial"

pickY :: Partial a b -> Maybe b
pickY (Y y) = Just y
pickY _ = Nothing
```

**Comment by sgraf812** [comment]
Wow, thanks! You are right, of course. That's also an elegant workaround, but I think for my case I can live with the monomorphic version for now.

I wonder, since you are mentioning that `Event` is not applicative, can you say where the laws don't hold? Or is it that you need `Moment` around for building up the graph?

**Comment by avieth** [comment]
> I wonder, since you are mentioning that Event is not applicative, can you say where the laws don't hold? 

I haven't even thought about whether the laws hold. The problem is even simpler: I see no way to give `pure :: t -> Event t`. That would have to be an event which fires at the beginning of time. Other frp packages like [frpnow](https://hackage.haskell.org/package/frpnow) give applicative events.

> Or is it that you need Moment around for building up the graph?

Yes that's also a problem. I played around with this in [reactive-sequence](https://github.com/avieth/reactive-sequence/blob/master/Reactive/Sequence.hs). Building-in an initial value and the `Moment` makes it possible to give an applicative instance. That's `SequenceBuilder` in the linked file, i.e. `type ApplicativeEvent t = Moment (t, Event t)`.
