### ISSUE TITLE
How can this library be installed with stack on macOS?

### ISSUE THREAD

**Issue by 2426021684** [HeinrichApfelmus/reactive-banana#144]
I am using stack on macOS Sierra. How can I install this library? Adding reactive-banana-wx to extra-deps gives an error but no information about why the build failed.

**Comment by ocharles** [comment]
Could you provide a full log?

**Comment by 2426021684** [comment]
http://lpaste.net/8538512301479690240

**Comment by jdreaver** [comment]
It looks like the problem is with `wxcore`.

**Comment by 2426021684** [comment]
https://sourceforge.net/p/wxhaskell/bugs/109/

**Comment by HeinrichApfelmus** [comment]
Closing this, as the problem appears to be with installing a dependency (`wxcore`). Sorry that I can't do much about it.
