### ISSUE TITLE
Clarification of execute's documentation

### ISSUE THREAD

**Issue by Kritzefitz** [HeinrichApfelmus/reactive-banana#145]
As discussed in [this StackOverflow question](http://stackoverflow.com/q/42191536/2211273) the documentation of the `execute` function in `Reactive.Banana.Frameworks` does not clearly specify which actions might be executed in a non-guaranteed order. Clarifying this, ideally with a code example, would be great.

**Comment by HeinrichApfelmus** [comment]
Thanks! I have expanded the documentation and added an example.
