### ISSUE TITLE
How can I poll an IORef on an interval / use Handler with threads?

### ISSUE THREAD

**Issue by mr** [HeinrichApfelmus/reactive-banana#146]
I'm trying to run some `IO` on another thread an monitor it over time (think: Monitoring the progress of a download). Right now I accomplish this by calling `async` and constantly writing updates to an `IORef` that my main thread polls. I want to use this with reactive banana to sink the value in the `IORef` to some element of my UI. I tried using `fromPoll`, but that seems to only get called when another input event fires which is not really what I want.

I also tried passing a `Handler` to my `async` thread and calling it with the state instead of using an `IORef` but no events were fired on my main thread as a result.

Is `Handler` supposed to work across threads like this (and I'm doing something else wrong), or is there some other way to accomplish this?

**Comment by HeinrichApfelmus** [comment]
Well, you somehow have to convert the state of your thread into an `Event` or `Behavior`.

One canonical way to do that is to use `newEvent` (or `newAddHandler`) and pass the result handler to the other thread. Reactive-banana is designed to be thread-safe, so this should work. If it doesn't, could be more specific about what exactly you did in your code, perhaps even providing a minimal example?

**Comment by mr** [comment]
I tried that so I probably was doing something else wrong. I just needed to hear that it was supposed to be thread safe.

**Comment by HeinrichApfelmus** [comment]
Ok! Of course, just because it is supposed to be thread-safe does not necessarily mean that it actually is, so please do report any issues.
