### ISSUE TITLE
Export more symbols in `Reactive.Banana.Prim`

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#156]
Hi, I see many unclickable words in the `Reactive.Banana.Prim` documentation:

- `EvalNetwork`
- `ReaderWriterIOT`
- `BuildR`
- `BuildW`
- `Ref`
- `Pulse'`
- `Latch'`

Is there a reason these are not exported, or should they be? Thanks!

**Comment by HeinrichApfelmus** [comment]
They are not exported, because they are for internal use only. Normally, one would wrap type synonyms in newtypes, so that stuff like this doesn't show up, but I didn't bother, because `Reactive.Banana.Prim` is not meant to be consumed by the ordinary user.
