### ISSUE TITLE
observeB combinator

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#157]
Hi, is it possible to efficiently implement this combinator?

```haskell
observeB :: Behavior (Moment a) -> Behavior a
```

**Comment by mitchellwrosen** [comment]
Oh, is this just `join . valueB`? :)

**Comment by mitchellwrosen** [comment]
... No... no it isn't... nevermind!

**Comment by HeinrichApfelmus** [comment]
No, I don't think that it can be implemented. For reasons of efficiency, `Behavior` internally carries around an Event that has an occurrence whenever the value changes. While `Moment` is very similar to `Behavior`, it does not carry around such a thing.

The closest you can get is indeed

    join . valueB :: Behavior (Moment a) → Moment a

**Comment by mitchellwrosen** [comment]
Got it, thanks!

**Comment by mitchellwrosen** [comment]
Hm, this made me realize that many combinators that involve `Behavior`+`Event` would also work equally well on `Moment`+`Event`:

```haskell
(<@>) :: Moment (a -> b) -> Event a -> Event b
(<@>) f e = observeE ((\x -> f <*> pure x) <$> e)

filterApply :: Moment (a -> Bool) -> Event a -> Event a
filterApply f e = observeE ((\x y -> (if f y then Just y else Nothing) <*> pure x) <$> e)

... etc ...
```

I think this could simplify some higher-order code I'm playing with right now that seems to require many `valueB`s, which feels inelegant.

**Comment by HeinrichApfelmus** [comment]
> I think this could simplify some higher-order code I'm playing with right now

I tend to concur. Higher-order code seems to work better by using a lot of `Moment`.
