### ISSUE TITLE
Fix reactive-banana-wx docs build failure

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#159]
Hi there, would it be possible to get the haddocks of `reactive-banana-wx` built on hackage? 

Here is the latest build error: https://hackage.haskell.org/package/reactive-banana-wx-1.1.1.0/reports/3

Thanks.

**Comment by ocharles** [comment]
@HeinrichApfelmus I can do this, but I'm not a maintainer for `reactive-banana-wx` - could you add me?

**Comment by HeinrichApfelmus** [comment]
@ocharles That would be great, tanks! I have added you to the maintainers on hackage, sorry about that, I didn't catch that there were two banana packages.

**Comment by ocharles** [comment]
I've uploaded some documentation, but it's come out a bit weird. I'll see what I can do, but will close this for now.
