### ISSUE TITLE
Combinator to map + filter an Event at the same time

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#160]
If I understand correctly, both `fmap` and `filterJust` _each_ add a new `Event` to the network. 

I wonder, is it possible to implement a primitive combinator that maps and filters at the same time, which would only add _one_ new `Event`?

If so, perhaps it could have this type, which is like the `push` combinator from `reflex`:

```haskell
mapE :: (a -> Moment (Maybe b)) -> Event a -> Event b
mapE f e = filterJust (observeE (fmap f e)) -- Inefficient... right?
```

`reflex` also has a pure variant:

```haskell
fmapMaybe :: (a -> Maybe b) -> Event a -> Event b
```

Thank you!

**Comment by ocharles** [comment]
Better would be fusion at the network level. One of the many reasons I like reactive-banana is because it isn't a huge combinator soup.

**Comment by HeinrichApfelmus** [comment]
I am happy to add new combinators if they are semantically useful or provide a substantial performance benefit (like `once`). But as far as I understand, this combination just adds a minuscule potential performance benefit, if at all?

**Comment by mitchellwrosen** [comment]
Oh, I was thinking it would be a substantial performance increase :sweat_smile: 

I'm happy to close this out... I agree with @ocharles that we should keep the number of derived combinators to a minimum.

**Comment by ocharles** [comment]
There might be a performance increase, but I still don't see why it can't be done when we assemble the underlying network. Shouldn't need a user facing combinator.

**Comment by HeinrichApfelmus** [comment]
The definition of "substantial performance increase" is a bit different in the land of Haskell than in the land of C. 😉

**Comment by mitchellwrosen** [comment]
Re: optimizing the event network, is any such fusion happening currently? Or, should I make a ticket for it? (Or not?) :)

**Comment by ocharles** [comment]
I can't think of any off the top of my head. I'm not sure about opening an issue until we can work out what bits are important to optimise. Just "make it faster" is a bit of a vague goal that is counter-intuitively not the best use of our time.

**Comment by mitchellwrosen** [comment]
@ocharles Circling back to this, do you have an idea about where in the code such an optimization framework might belong?
