### ISSUE TITLE
`switchE` with an initial event

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#162]
Hi, I have some code that I can't quite figure out how to implement with the existing API. I think I want a variant of `switchE` that takes an initial `Event` to act as, until the event-of-events fires.

```haskell
switchE' :: MonadMoment m => Event a -> Event (Event a) -> m (Event a)
```

Semantics are something like this (basically `switchE`, but I think the first event might be special in that if it's emitting in the first moment, it's not dropped. That way, `switchE' e never = pure e`):

```
switchE :: [(Time, a)] -> [(Time, [(Time, a)]) -> Time -> [(Time, a)]
switchE e0 ee t0 =
  case e' of
    []  ->  [(tx, x) | (tx, x) <- e0, t0 <= tx]
    (t1, _) : _ -> [(tx, x) | (tx, x) <- e0, t0 <= tx, tx <= t1] ++ e'
  where
    e' :: [(Time, a)]
    e' = concat [trim t1 t2 e | (t1, t2, e) <- intervals ee, t0 <= t1]

    intervals e :: [(Time, a)] -> [(Time, Time, a)]
    intervals e = [(t1, t2, x) | ((t1, x), (t2, _)) <- zip e (tail e)]

    trim :: Time -> Time -> [(Time, a)] -> [(Time, a)]
    trim t1 t2 e = [(tx, x) | (tx, x) <- e, t1 < tx, tx <= t2]
```

Is this possible to implement somehow?

**Comment by ocharles** [comment]
Are you able to provide a motivating example of why you would need this combinator?

**Comment by mitchellwrosen** [comment]
Sure. Say I have two input events: `Int` (set the factor) and `()` (tick):

```haskell
eFactor :: Event Int <-
  fromAddHandler factorAddHandler

eTick :: Event () <-
  fromAddHandler tickAddHandler
```

Now say my program state is a `Behavior Int` that starts at 0 and increments by the current factor every tick.

```haskell
let eValueGen :: Int -> Moment (Event Int)
    eValueGen fact = do
      val <- valueB bValue
      accumE val ((+ fact) <$ eTick)

-- The initial event: initialize to a factor of 1
eValueFirst :: Event Int <-
  eValueGen 1

-- The event of events to switch to
let eValueNext :: Event (Event Int)
    eValueNext = observeE (eValueGen <$> eFactor)

-- The whole event: behave as eValueFirst until eValueNext fires
eValue :: Event Int <-
  switchE' eValueFirst eValueNext

bValue :: Behavior Int <-
  stepper 0 eValue
```

Here I used my variant of `switchE` because not only do I want to switch to a new `Event Int` every time `eFactor` fires, I also have an `Event Int` I want to behave as _before_ `eFactor` ever fires.

This simple example is probably much cleaner using first-order events/behaviors, but I still think it should be possible to implement in a higher-order style.

**Comment by mitchellwrosen** [comment]
After a bit of thinking I was able to restructure my logic and now I no longer need this operator. My problem was roughly equivalent to "I wish events defined with `accumE` fired in the first moment of time with the initial value", which is just not how the library works!

**Comment by ocharles** [comment]
I was surprised that there were programs that couldn't be expressed without this combinator. If you do end up finding some, please comment again, but for now I'll close this.

**Comment by mitchellwrosen** [comment]
Turns out this combinator has existed all along!

```
switchE' :: MonadMoment m => Event a -> Event (Event a) -> m (Event a)
switchE' e es = stepper e es >>= valueB
```

**Comment by mitchellwrosen** [comment]
So, nevermind that last comment, there is no switching occurring there. The returned `Event` is equivalent to the first argument.

Then, @ocharles I may have an example of a program that can't be written with higer-order reactive-banana today: the first example from this article https://blog.qfpl.io/posts/reflex/basics/switching/

It's basically isomorphic to my dummy example, but anyways it goes something like this. Say we have an event that fires when an "Add" button is clicked:

```haskell
eAdd :: Event ()
```

We also have "on" and "off" buttons...

```haskell
eOn :: Event ()
eOff :: Event ()
```

Now we want to make a single `Event ()` that fires whenever `eAdd` fires, but only if our state is "on" (initialized to on, and toggled by `eOn`/`eOff`).

This is easy with first-order style...

```haskell
bIsOn :: Behavior Bool <-
  stepper True (unionWith const (True <$ eOn) (False <$ eOff))

let eFire :: Event ()
    eFire = whenE bIsOn eAdd
```

...but doesn't seem possible with just `switchE`, since there is the concept of an event that exists at the beginning of time.

Looking at the code, it seems trivial to upgrade `switchE` to be more powerful in the way that I'm describing: https://github.com/HeinrichApfelmus/reactive-banana/blob/7b120be3667488cfb46f48cef32bf91c5fbbb366/reactive-banana/src/Reactive/Banana/Prim/Combinators.hs#L123

Instead of initializing the first `Pulse` to `never`, just take it as an additional argument.

**Comment by HeinrichApfelmus** [comment]
Ah, I see. Since `switchE` does not switch to a new event until after the switching event has fired, it can never fire at the first occurrence of the first event in the switch. However, `switchE'` can do that, so it's clear that the former combinator cannot be used to directly implement the latter combinator.

**Comment by PaulJohnson** [comment]
I've just run into a need for this one too. I have a GTK "Notebook" with a number of tabs, each of which returns an `Event a` for updates. I need to track the events from the currently open tab while ignoring events from other tabs. I track the current tab using `tabUpdates :: Event (Event a)`. `switchE tabUpdates` works fine, but only after the user has changed tabs.

Unfortunately this is in a GUI where a change to one widget can trigger updates to others, so the non-selected tabs receive input events when the current value changes. This can cause each one to trigger new update events. Hence I have to ignore events from the non-selected tabs.

**Comment by PaulJohnson** [comment]
Here is my clunky work-around

`-- | A version of "switchE" which takes an initial event stream to`
`--  match the semantics of "switchB"`
`switchE1 :: (MonadMoment m) => Event a -> Event (Event a) -> m (Event a)`
`switchE1 i es = do`
`    allow <- stepper True $ False <$ es`
`    unionWith const (whenE allow i) <$> switchE es`

**Comment by ocharles** [comment]
@PaulJohnson's proposal is a nice one, but I think it means that `i`  will never be garbage collected. Interestingly this is related to https://github.com/HeinrichApfelmus/reactive-banana/issues/74 - but it's a bit more than just `once`. It's more `upTo :: Event a -> Event b -> Moment (Event a)`, which is "all occurences of `Event a`, until the next occurrence of `Event b`). With that `upTo` combinator, I think you could even say `once e = upTo e e`. The question is, which is the better primitive? Is it `upTo`, and defining `switchE1` in terms of that, or is it `switchE1`, and `upTo a b = switchE1 a (never <$ b)`?

**Comment by ChristopherKing42** [comment]
I kind of like the `upTo` combinator better. It could be given the type `upTo :: Event a -> Event () -> Moment (Event a)` instead though; I'm not sure which signature is better.

**Comment by ocharles** [comment]
`switchE` now takes an initial event, so I think this issue is fixed! :tada:
