### ISSUE TITLE
Difference between `switchE`/`switchB` and `valueB`?

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#164]
Hi, I recently realized that you can implement both `switchE` and `switchB` using just `stepper` and `valueB`:

```haskell
switch :: MonadMoment m => a -> Event a -> m a
switch x xs = join (fmap valueB (stepper x xs))

switchE = switch never
switchB = switch
```

I tried digging through the code to understand what the difference is, but I'm afraid I can't understand any of it :(

Is there a difference between these two implementations in terms of when events can be garbage collected? Or, any other notable differences worth mentioning in the documentation?

Thanks!

**Comment by HeinrichApfelmus** [comment]
That looks interesting, but I think the result of this combinator is simply the first argument. Did you check a few test cases with `interpret` or try to reason more formally with the semantics from the `Reactive.Banana.Model` module?

**Comment by mitchellwrosen** [comment]
Oh, of course... that's how `valueB` works ;) Sorry about that.
