### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#170]
@HeinrichApfelmus I've cut a candidate release here: https://hackage.haskell.org/package/reactive-banana-1.2.0.0/candidate. If this is OK, I'll finalise the release.

**Comment by HeinrichApfelmus** [comment]
Thanks! Looks good to me! Is there anything in particular I should look for?

That said, there is a warning about specifying the Cabal version, but I do not understand it. Up to you.

**Comment by ocharles** [comment]
Nope, just wanted to make sure the HEAD of this repository is what you wanted to release, and that the changelog is OK.

**Comment by HeinrichApfelmus** [comment]
Yes and yes. Thanks, Oliver!

**Comment by ocharles** [comment]
Published!
