### ISSUE TITLE
Why does `cache` require `MonadFix`?

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#176]
Here is the implementation of `Reactive.Banana.Prim.Cached.cache`:

```haskell
{-# NOINLINE cache #-}
cache :: (MonadFix m, MonadIO m) => m a -> Cached m a
cache m = unsafePerformIO $ do
    key <- liftIO $ newIORef Nothing
    return $ Cached $ do
        ma <- liftIO $ readIORef key    -- read the cached result
        case ma of
            Just a  -> return a         -- return the cached result.
            Nothing -> mdo
                liftIO $                -- write the result already
                    writeIORef key (Just a)
                a <- m                  -- evaluate
                return a
```

I'm curious, what is the purpose of the recusive-do here?

```haskell
liftIO $ writeIORef key (Just a)
a <- m
return a
```

I don't quite understand why this isn't written as:

```haskell
a <- m
liftIO $ writeIORef key (Just a)
return a
```

My only guess is this is meant to prevent the action from accidentally being executed twice in the presence of concurrency (but why does this matter? - Well maybe that's a separate question :)), but that can still happen with the current implementation.

Thanks!

**Comment by mitchellwrosen** [comment]
I think I have the answer. It's not to do with concurrency, because a lock is taken to step the network, but allows the computation to be self-referential without bottoming out.

**Comment by HeinrichApfelmus** [comment]
Yes, this is the answer. This is important, because it allows Behavior to recursively depend on Event.

**Comment by HeinrichApfelmus** [comment]
Not necessary, better keep this secret. :wink: I think Google will pick it up fine.

**Comment by ocharles** [comment]
Based on the last two replies, looks like we're good on this one!
