### ISSUE TITLE
Combine `Future`, `changes` and `reactimate'`

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#179]
If I'm not mistaken, the only thing the API allows you to do with the `Event (Future a)` returned by `changes` is `reactimate'` it.

The docs around `Future`, `changes`, and `reactimate'` are very informative, so they should stick around somehow, but I wonder if the API could be simplified to:

```haskell
fooblah :: Behavior (IO ()) -> MomentIO ()
```

**Comment by mitchellwrosen** [comment]
Whoops, I just realized you are allowed to use the `Event (Future a)` in other parts of the network definition itself. I've just never done that.. I only end up using `changes` in little CLI apps whose state is in a Behavior, and I want to see the very latest state upon e.g. pressing a key.

**Comment by HeinrichApfelmus** [comment]
You can use `e :: Event (Future a)` in other way than just `reactimate'`. For instance, you can do`() <$ e :: Event ()` and apply `unionWith`. This is useful when communicating with external GUI libraries.
