### ISSUE TITLE
Event (IO a) -> Event a

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#180]
There are a few similar functions in `reactive-banana`:

```haskell
observeE :: Event (Moment a) -> Event a
execute :: Event (MomentIO a) -> MomentIO (Event a)
mapEventIO :: (a -> IO b) -> Event a -> MomentIO (Event b)
```

Commonly I find myself wanting a bit of randomness to occur on some event occurrence, which requires IO. Currenly, I've been using `execute`, though the `MomentIO` context makes things look a bit awkward.

For example, I'd like to write some `accumB` as

```haskell
b <- accumB x [ e1, e2, e3, e4, e5 ]
```

but if `e4` and `e5` require IO, then I have to write

```haskell
b <- do
  e4 <- execute f
  e5 <- execute g
  accumB x [ e1, e2, e3, e4, e5 ]
```

My question is: _if_ the inner `MomentIO` is restricted to just `IO`, would it be possible to strip off the `MomentIO` in the return value, similar to `observeE`'s type? As in:

```haskell
observeIO :: Event (IO a) -> Event a
```

If the type makes sense semantically, it would greatly simplify the randomness use case, which I assume is common.

An aside: if I can assume that an `a` in `Event a` is only evaluated once, as I believe is the case due to the `Cached` machinery, is `observeIO` equivalent to `fmap unsafePerformIO`?

**Comment by hololeap** [comment]
`MomentIO` is essentially something like `ReaderT (r, IORef w) IO`, so there's no safe way to extract `Event a` from the `IO` monad. I don't see how you would write it much better than the second example you gave.

**Comment by HeinrichApfelmus** [comment]
In general, IO actions have to be arranged in a sequence. The proposed combinator `observeIO` would raise the question: "Where in this sequence does the IO action occur?" but there would be no way to give a deterministic answer — this IO action would occur in some unknown order relative to the others. That is how `execute` and `mapEventIO` behave, and that is why they are confined to the `MomentIO` monad, which serves as a big warning sign. In contrast, all combinators from the `Reactive.Banana.Combinators` module have a well-defined, deterministic semantics.

**Comment by mitchellwrosen** [comment]
Right, excellent point @HeinrichApfelmus! Should I close the issue?
