### ISSUE TITLE
An interesting `Behavior` type

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#187]
I noticed [`purescript-behaviors`](https://github.com/paf31/purescript-behaviors/blob/f55fd957500e9a70d21e1f20e95f8dc0696724ef/src/FRP/Behavior.purs#L43) defines an interesting Behavior type:

```haskell
data Behavior a
  = Behavior (forall b. Event (a -> b) -> Event b)
```

I haven't played around with that API, just thought I'd bring it up here for discussion in case you haven't seen that particular flavor of Behavior before :)

**Comment by HeinrichApfelmus** [comment]
That is interesting definition indeed. It essentially defines a Behavior to be the thing that gives you the `(<@>) :: Behavior (a → b) → Event a → Event b` function.

    toPurescript_Behavior :: Behavior a → (Event (a → b) → Event b)
    toPurescript_Behavior b e = flip ($) <$> b <@> e

I don't think it's useful for the implementation here, but it may be useful for the `Model` module.

**Comment by mitchellwrosen** [comment]
Thanks!
