### ISSUE TITLE
A combination of reactimate and execute

### ISSUE THREAD

**Issue by Simre1** [HeinrichApfelmus/reactive-banana#194]
Would it be possible to have a function with the type:
`Event (EventMomentIO ()) -> MomentIO ()` with _EventMomentIO_ being an instance of _MonadMoment_ as well as _MonadIO_.

Is there a way to achieve this with the current version of reactive-banana? If not, might someone be able to give me a hint on how to fork the library without breaking anything?

**Comment by mitchellwrosen** [comment]
What is `EventMomentIO`? Note that `MomentIO` already has a `MonadIO` instance.

**Comment by mitchellwrosen** [comment]
Sorry, I don't really follow :(

Note that outputs (reactimate) are required to keep events "alive". This is mentioned in the docs somewhere, but the gist of it is, you can't drop an `Event a` on the floor and expect the underyling `IO` actions that produce those `a`s to continue to fire.

**Comment by Simre1** [comment]
Ok, I will try to explain more clearly what I want to do with an example.

```
type MyStack m a = ReaderT (Behavior String) m a

printString :: (MonadMoment m, MonadIO m) => MyStack m ()
printString = do
  behaviorString <- ask
  currentString <- lift $ liftMoment $ valueB behaviorString
  liftIO $ putStrLn currentString
```

If I want to execute printString whenever an event happens, I would need a function like the following:
```
reactimateMyStack :: (MonadMoment m, MonadIO m) => (MyStack m a -> m a) -> Event (MyStack m ()) -> MomentIO ()
reactimateMyStack runMyStack event = customReactimate (runMyStack <$> event)

customReactimate :: (MonadMoment m, MonadIO m) => Event (m ()) -> MomentIO ()
```
I could use `execute` to define `customReactimate`:

```
customReactimate :: Event (MomentIO ()) -> MomentIO ()
customReactimate event = execute event >> return ()
```

However, from what I can understand from the [documentation](https://hackage.haskell.org/package/reactive-banana-1.2.0.0/docs/Reactive-Banana-Frameworks.html#v:execute) of `execute`, there is a chance that the `MomentIO` actions are never executed.

My questions now are:
- Is the use of `execute` in `customReactimate` safe? 
- If not, can I somehow make it safe and ensure the execution of my `MomentIO` actions?

**Comment by mitchellwrosen** [comment]
In `customReactimate`, your resulting `Event ()` is dropped on the floor. You need to attach an output node to it with `reactimate` in order to reliably execute the `IO` actions that create each `()`.

For example:

```haskell
customReactimate :: Event (MomentIO ()) -> MomentIO ()
customReactimate event = do
  event' <- execute event
  reactimate (pure <$> event')
```

Does that help?

**Comment by Simre1** [comment]
Yes, thank you for your help!
I already did something similar with `execute event >>= reactimate . (fmap pure)`, but I was not sure if it would do the trick.
