### ISSUE TITLE
Build fails under GHC 8.6.3 due to containers dependency

### ISSUE THREAD

**Issue by PaulJohnson** [HeinrichApfelmus/reactive-banana#195]
Cabal dependency includes `containers (==0.5.*)`, but latest GHC has containers-0.6.

**Comment by mitchellwrosen** [comment]
I just noticed this was fixed in `1.2.1.0`

**Comment by ocharles** [comment]
Thanks @mitchellwrosen. Indeed - I released 1.2.1.0 yesterday which contains https://github.com/HeinrichApfelmus/reactive-banana/pull/191.
