### ISSUE TITLE
Offer to help maintain this repo

### ISSUE THREAD

**Issue by mitchellwrosen** [HeinrichApfelmus/reactive-banana#197]
Hello folks, I am willing to help maintain this repo if you'd like!

**Comment by HeinrichApfelmus** [comment]
Thanks for the offer! Sorry for not having a lot of time lately. Most of the recent issues are design questions that I can't just yay or nay without considering the wider consequences for the API. For "day-to-day" operations with minor fixes, @ocharles kindly comaintains this package. Thanks Charles! Do you need an extra hand?

If you want to help out: I do feel that many issues are actually questions and discussion. Perhaps setting up a dedicated discussion forum might be a good idea? Along the lines of [Discourse][1] and the recent [discourse.haskell.org][2].

  [1]: https://www.discourse.org
  [2]: https://discourse.haskell.org

**Comment by mitchellwrosen** [comment]
No worries! Indeed there are many issues/questions in the tracker that are random and not in need of immediate attention.

My offer to help maintain this repo was partially motivated by these PRs. I'm just not sure how to get some more eyes on them.

- https://github.com/HeinrichApfelmus/reactive-banana/pull/163
- https://github.com/HeinrichApfelmus/reactive-banana/pull/165

If you could find time to accept or reject them, that would be greatly appreciated!

**Comment by ocharles** [comment]
I'd be happy to have @mitchellwrosen have a commit bit on this repo - I generally favour giving them out liberally.

**Comment by mitchellwrosen** [comment]
Hello again, the offer still stands :)

I'd also like to get this package on stackage. I'd be happy to be the stackage maintainer as well.

**Comment by ocharles** [comment]
I think it's a shame we missed this offer. @mitchellwrosen if this still stands, I'd love to have you on board. We clearly need help, as I don't think either me or @HeinrichApfelmus have the time needed for this project.

**Comment by HeinrichApfelmus** [comment]
I am very sorry for not responding anywhere near in time. 😔 I am still unable to spend as much time on Haskell projects as I would like to — and life just threw me another curveball. I concur with Oliver: If you offer still stands, @mitchellwrosen , I'd be happy to take it — and this time, in time.

**Comment by mitchellwrosen** [comment]
Folks, no worries! I'm in mobile so I will make a follow-up comment later, but I realize I rather rudely closed the issue with no comment. I was just going through my Git Hub notifs and closing things out, and this issue seemed inactive. Apologies! 👍

**Comment by ocharles** [comment]
@mitchellwrosen Nudge :)

**Comment by mitchellwrosen** [comment]
Hello again.

Sure, I'm still willing to help maintain this repo. I really never found the time to understand the implementation, so I don't know how _useful_ I can be - but we'll see! :)

**Comment by ocharles** [comment]
That's fine! I think we'd really appreciate just having someone who can do trivial dep bumps, merge obvious PRs and cut releases to Hackage. If you're interested in that, @HeinrichApfelmus could you hand out the appropriate keys?

**Comment by HeinrichApfelmus** [comment]
Yes, indeed. I have trouble finding the time even for seemingly trivial things, such as dep dumps like #206 . @mitchellwrosen , you also mentioned maybe including this package into Stackage?

**Comment by HeinrichApfelmus** [comment]
I have invited you as a collaborator. I appreciate any help, especially with things relating to infrastructure. I tend to be a bit more conservative on API-related issues, but please do feel free to bring pressing issues to my attention, I'll try to look into it. For example, #173 seems like a low-hanging fruit.

Apologies for the fact that the internals are hard to understand as well. At some point, I want to document them properly, but I feel that this warrants a research paper / whitepaper, and I currently do not have the resources to do that.

**Comment by mitchellwrosen** [comment]
Great, I'll close this out now. Thanks!

**Comment by mitchellwrosen** [comment]
@HeinrichApfelmus Could you add me as a maintainer on Hackage as well? My username there is `mitchellwrosen`

**Comment by HeinrichApfelmus** [comment]
Yes, of course. Done. Thanks!
