### ISSUE TITLE
Suggestion: More general `unionWith`

### ISSUE THREAD

**Issue by ChristopherKing42** [HeinrichApfelmus/reactive-banana#203]
How about a version of `unionWith` with this more general type:

```unionWith' :: (a -> c) -> (b -> c) -> (a -> b -> c) -> Event a -> Event b -> Event c```

which uses the first function if the first event fires alone, the second function if the second event fires alone, and the third function if they fire simultaneously.

This could theoretically be written using the current `unionWith` using `Either` values, but that would involve incomplete pattern matches, which is kind of ugly. `unionWith` could be written in terms of `unionWith'` rather nicely though. Another nice combinator derived from `unionWith'` is one with the type `(Just a -> Just b -> c) -> Event a -> Event b -> Event c`.

**Comment by HeinrichApfelmus** [comment]
This seems to be related to #163

**Comment by ChristopherKing42** [comment]
Oh, it does! I kind of like not using not including Maybes in the type sig though, since you can just apply a filter just to achieve that.

**Comment by mitchellwrosen** [comment]
I am preparing to make a minor version release to include `mergeWith`, but I do like this suggestion @ChristopherKing42. Naming aside, I can't really tell which which version is more convenient nor which is more fundamental:

```haskell
-- What's implemented now
mergeWith :: (a -> Maybe c) -> (b -> Maybe c) -> (a -> b -> Maybe c) -> Event a -> Event b -> Event c

-- Your suggestion
mergeWith :: (a -> c) -> (b -> c) -> (a -> b -> c) -> Event a -> Event b -> Event c
```

Any thoughts on this @HeinrichApfelmus or @ocharles?

**Comment by ocharles** [comment]
@mitchellwrosen to suggest yet another colour for this bikeshed:

```haskell
mergeWith :: (These a b -> c) -> Event a -> Event b -> Event c
```

Or, more generally:

```haskell
instance Semialign Event
```

**Comment by mitchellwrosen** [comment]
Oh, I like `instance Semialign Event` a lot!

I'm curious how many new transitive dependencies `semialign` would bring in. If it's not too many, that instance seems worth it to me! :) (But I defer to @HeinrichApfelmus/@ocharles  in general about adding new deps).

**Comment by mitchellwrosen** [comment]
New transitive deps `semialign-1.1.0.1` would bring in:

```
StateVar 1.2.2
assoc 1.0.2
base-orphans 0.8.4
bifunctors 5.5.11
comonad 5.0.8
contravariant 1.5.5
distributive 0.6.2.1
indexed-traversable 0.1.1
primitive 0.7.1.0
semialign 1.1.0.1
semigroupoids 5.3.5
stm 2.5.0.0
tagged 0.8.6.1
th-abstraction 0.4.2.0
these 1.1.1.1
transformers-compat 0.6.6
```

**Comment by mitchellwrosen** [comment]
Another option would be to depend on `these`, but not `semialign`.

I like the idea of consistently naming this operation, perhaps with an E at the end just to avoid shadowing the general version:

```haskell
align :: Event a -> Event b -> Event (These a b)

alignWith :: (These a b -> c) -> Event a -> Event b -> Event c
```

**Comment by ocharles** [comment]
> My thoughts, fwiw, are to go with your preferred version of mergeWith, as we could always generalize with the added dep(s) later.

@mitchellwrosen To confirm, you're happy with me to add

```haskell
mergeWith :: (a -> c) -> (b -> c) -> (a -> b -> c) -> Event a -> Event b -> Event c
```

for now? Then if people want to use `semilagin`, they can: `mergeWith This That These`?

**Comment by mitchellwrosen** [comment]
Yup, that's the signature! I'm less sure about the name. Here are a couple thoughts which hopefully won't slow you down too much as we get the release out the door. -

1. There's no `merge` that doesn't take additional args so the `With` seems superfluous. All else being equal I think a shorter name like `merge` wins out.
2. ... but why `merge` and not `mergeE`? The API is kind of already inconsistent here.
3. Is `merge` the right verb given that this pattern has been somewhat standardized as "(semi-)align"?

But I'm good with anything, including `mergeWith`, it's just not my personal first choice.

**Comment by ocharles** [comment]
There's also the option of a breaking change and changing `unionWith` to this more generalized type. I'm not sure what our policy is on breaking changes though. Wrt

> There's no merge that doesn't take additional args so the With seems superfluous. All else being equal I think a shorter name like merge wins out.

Note there is also no `union`, but we do have `unionWith`. I'm thinking of erring on the side of consistency. Also worth noting that is `Data.Semialign`, `alignWith` is the "with eliminator" version, and `align` produces a `These a b`. I think that's a good model to copy (so `merge :: Event a -> Event b -> Event (These a b)`).

Let me just check what downstream libraries would be impacted by this change

**Comment by ocharles** [comment]
* `feed-gipeda` would be impacted (https://github.com/sgraf812/feed-gipeda/blob/84df8d1ffa8086ff531be9447d06ce6a03c386d8/src/FeedGipeda/Master.hs#L206)
* `reactive-banana-automation` would be impacted, but only in the examples.
* `reactive-banana-bunch` would be impacted (https://hub.darcs.net/thielema/reactive-banana-bunch/browse/src/Reactive/Banana/Bunch/Combinators.hs#43)
* `reactive-banana-sdl2` would be impacted (https://github.com/cies/reactive-banana-sdl2/blob/c3bc18adad7cb761aa380433af75752ec0912ebd/src/Reactive/Banana/SDL2/Util.hs#L87)

So breaking `unionWith` does have some impact

**Comment by mitchellwrosen** [comment]
Ah, good points!

I had not yet considered just generalizing`unionWith`. I think I do like that, though the breakage hurts, because semantically this "merge" is indeed just a union, now that it's not returning Maybes that can filter occurrences out.

However, I find `foldr (unionWith const) never` rather convenient for when the Event does not contain a monoid and thus can't be combined with another using `<>`.

This would then become `foldr (unionWith id id const) never`, which is quite a mouthful. Perhaps that should be its own combinator, `leftmostE`?

**Comment by mitchellwrosen** [comment]
cc @sgraf812 @cies @joeyh @thielema who may have valuable input, as possibly-affected maintainers

**Comment by HeinrichApfelmus** [comment]
Sorry for having gone AWOL! The good news is that I spend more time with Haskell these days.

I like including both

    mergeWith :: (a → c) → (b → c) → (a → b → c) → Event a → Event b → Event c
    merge :: Event a → Event b → Event (These a b)

and I would prefer to keep `unionWith` as it is for backward compatibility. The nomenclature `union…` and `merge…` matches nicely with the nomenclature for `Data.Map.*` which has both 'union' (where both types are equal) and ['merge'](https://hackage.haskell.org/package/containers-0.6.5.1/docs/Data-Map-Merge-Strict.html#v:merge) (where input types are different).

**Comment by ocharles** [comment]
@HeinrichApfelmus Woohoo, nice to have you back :hugs:

Ok, let's go with a dependency on `these` and add `mergeWith` and `merge`. I certainly think that's the proper thing to do.
