### ISSUE TITLE
Request: Less restrictive bounds for package deps on hackage

### ISSUE THREAD

**Issue by ErnestKz** [HeinrichApfelmus/reactive-banana#215]
Hi,

Would it be possible to bump the version of `hashable` and `semigroups` to  `<1.3.2` and `<0.19.1` on hackage? 

This would help out fixing this issue https://github.com/NixOS/nixpkgs/pull/125893 and `un-break` the package in the nixpkgs snapshot without needing to manually override.

Thank you.

**Comment by mitchellwrosen** [comment]
Sure, I think that could be accomplished one of two ways... 

- We could make a release, which looks like it would just be a minor version bump to 1.2.2 to include `mergeWith` https://github.com/HeinrichApfelmus/reactive-banana/pull/163
- We could just make a revision on Hackage to relax the bounds. (Downside: hackage metadata gets out of sync with the git repo...)

**Comment by ErnestKz** [comment]
Whichever is most appropriate!  

We've decided to add an [override](https://github.com/NixOS/nixpkgs/commit/bd103151ea885a9802fa25f359f19ed0a0e162ef) for the time being in nixpkgs, which is aimed to merge by [2021-06-11](https://github.com/NixOS/nixpkgs/pull/125429).

So I think avoid gettings things out of sync (although I'm not sure what the implications are and maybe it's not annoying at all). 

And if it's not time yet for a release then that can be delayed as well I think.

**Comment by HeinrichApfelmus** [comment]
@mitchellwrosen If you want to go ahead with either path, feel free to do so. Thanks!
