### ISSUE TITLE
Add `@>`

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#227]
We have `<@`, but I would argue that `@>` is actually the more useful combinator. This would be:

```haskell
(@>) :: Event a -> Behavior b -> Event b
```

The reason I call this combinator more useful is because we now have `ApplicativeDo`, which lets us easily sample multiple `Behavior`s:

```haskell
reactimate $ onFoo @> do
  x <- xs
  y <- ys
  return (x + y)
```

This is difficult to write so succinctly with the current combinators.

**Comment by HeinrichApfelmus** [comment]
I like the idea! But: What fixity and what associativity should it have?

A function combined with ($) could perform a similar job:

sample :: Event a → Behavior b → Event b
sample = flip (<@)


reactimate $ sample onFoo $ do
   x <- xs
   y <- ys
   pure $ x+y

(Sorry for the formatting, I'm on mobile)

**Comment by ocharles** [comment]
Sorry I should have said that this would mirror the already existing $> in Data.Functor

**Comment by ocharles** [comment]
I should also say I'm a big fan of having infix operators also have a named equivalent - so `sample` would be an equally welcome addition!
