### ISSUE TITLE
Release 1.3.0.0

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#249]
It's been a while since we last released! This release will need to big a major version bump due to (at least) the `switchE` change and the new `.Prim` hierarchy. @HeinrichApfelmus @mitchellwrosen What do you think - shall we cut a new release?

**Comment by HeinrichApfelmus** [comment]
Yes please! 😊

**Comment by ocharles** [comment]
Done! https://hackage.haskell.org/package/reactive-banana-1.3.0.0

**Comment by ocharles** [comment]
Whoops, I forgot to update the changelog with the date :facepalm: Oh well, 1.3.1.0 can have that!
