### ISSUE TITLE
Join Stackage

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#250]
A reminder to myself to submit `reactive-banana` to Stackage. @HeinrichApfelmus @mitchellwrosen can I list you both as Stackage maintainers (along with myself)?

**Comment by HeinrichApfelmus** [comment]
The main reason why I never considered adding reactive-banana to Stackage is that they had fairly tight responsiveness requirements. They have relaxed that (quote below), but I still feel that I personally won't be able to be very responsive. However, it's possible to add a package without being the main maintainer — for example, Simon Jakobi kindly takes care of Stackage released for threepenny-gui . So, as long as you keep my name out of the Stackage maintainers list, feel free to upload it there. 😊 

----

> Previously we had stricter time limits, but we decided to remove that: Anyone is free to add a package to Stackage regardless of responsiveness guarantees. However, as stated above, we may elect to temporarily remove a package if it is not updated in a timely manner.

from https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by ocharles** [comment]
Cool! I have some of my libraries there and have found it generally a positive experience, so I'll submit and take on the maintenance 😊

**Comment by HeinrichApfelmus** [comment]
Thanks, Ollie! 😊

**Comment by ocharles** [comment]
Done! https://github.com/commercialhaskell/stackage/pull/6512
