### ISSUE TITLE
Not compatible with these-1.2 (disallowed)

### ISSUE THREAD

**Issue by ysangkok** [HeinrichApfelmus/reactive-banana#285]
These-1.2 is the first release compatible with assoc-1.1, which is the only release compatible with bifunctors-5.6.1.

**Comment by HeinrichApfelmus** [comment]
Thanks for the heads-up. I have published a new revision on hackage and merged a pull request to `master`. Does that resolve your tension?

**Comment by ysangkok** [comment]
Thank you, yes it works, I am adding the package back to Stackage:
* https://github.com/commercialhaskell/stackage/pull/6967
