### ISSUE TITLE
Simultaneous events can have undefined behavior within execute

### ISSUE THREAD

**Issue by asivitz** [HeinrichApfelmus/reactive-banana#287]
(reactive-banana 1.3.2.0, GHC 9.2.7)

I have a large, complex network that drops some simultaneous events (picking one or the other randomly instead of allowing me to choose). I found that it is related to the fact that the network is dynamically added. I believe I have a minimal-ish reproduction case. It might be possible to make it a little simpler.

```
{-# LANGUAGE RecursiveDo, ScopedTypeVariables #-}
module Main (main) where

import Reactive.Banana
import Reactive.Banana.Frameworks

main :: IO ()
main = do
  (addHandlerFirst, fireFirst) <- newAddHandler
  (addHandlerSecond, fireSecond) <- newAddHandler
  compile (outer addHandlerFirst addHandlerSecond) >>= actuate
  fireFirst (1 :: Int)
  fireSecond (2 :: Int)
  where
  outer ahFirst ahSecond = do
    eFirst  <- fromAddHandler ahFirst
    eSecond <- fromAddHandler ahSecond

    -- We should eventually receive an error for simultaneous events

    -- Use this line instead of the other one to avoid the error
    -- b :: Behavior Int <- execute (inner eSecond <$ eFirst) >>= switchB (pure 0)
    -- Use this line to get the error
    -- b <- inner eSecond


    reactimate $ (\a -> print ("Fired: " ++ show a)) <$> b <@ eSecond

  inner eSecond = mdo
    -- We'll tie a couple knots, to get events that should fire simultaneously
    (eDerivOne :: Event (), _b1) <- mapAccum () $
      -- Shout if we detect simultaneous events
      unionWith (error "Simultaneous")
      (const ((),()) <$ eSecond)
      (const ((),()) <$ eDerivTwo)

    (eDerivTwo :: Event (), b2) <- mapAccum 5 $
      unionWith const
      (const ((),3) <$ eDerivOne)
      (const ((),4) <$ eSecond)

    pure b2
```

**Comment by HeinrichApfelmus** [comment]
Hm. 🤔  I think that this is actually an instance of #228 — this network is not supposed to work at all, as the function `inner` describes an ill-defined network. Only mutual recursion between `Event` and `Behavior` should work.

**Comment by asivitz** [comment]
Ah okay, that makes sense. I guess in my network it is somewhat reasonable b/c filters will stop infinite recursion, but it makes sense that it would not be generally acceptable. And I can see a better architecture for my situation anyway.

Thanks for a taking a look, and for the great library!
