### ISSUE TITLE
Accept deepseq-1.5

### ISSUE THREAD

**Issue by ysangkok** [HeinrichApfelmus/reactive-banana#294]
Nightly now has this version of deepseq, it would be nice if reactive-banana supported it. Then it could get back into Nightly, assuming no other blockers. Which I have not checked for.

**Comment by HeinrichApfelmus** [comment]
Which Nightly do you mean? Stackage Nightly? GHC Nightly?

I believe that `deepseq-1.5` should work as well — I have made a revision on Hackage.

Let me know if there are any problems.

**Comment by ysangkok** [comment]
Works! Thank you.
