### ISSUE TITLE
Add Num instance for Behavior

### ISSUE THREAD

**Issue by sjoerdvisscher** [HeinrichApfelmus/reactive-banana#34]
Since GHC 7.4.1 `Eq` and `Show` are no longer superclasses of `Num`.

**Comment by ocharles** [comment]
I realise I never voiced my opinion here. I'd like to mention that I am quite strongly :+1: on `Num`, `Fractional` and `Floating` instances.

**Comment by ocharles** [comment]
Can we open some more dialog on this? I don't really buy the only comment against this - if you try and use operators that aren't part of `Num`, you get a type error as expected. That's mildly annoying, but not a disaster. The `Num` operators remove a significant amount of noise, especially in game related programming.

**Comment by HeinrichApfelmus** [comment]
I'm in favor now. See #174
