### ISSUE TITLE
Potential Bug: usage of unsafePerformIO?

### ISSUE THREAD

**Issue by fbinz** [HeinrichApfelmus/reactive-banana#37]
In `Reactive.Banana.Internal.PulseLatch0` you are using `unsafePerformIO` several times without using a `NOINLINE` pragma. Is this intentional or could problems as described in [the documentation](http://www.haskell.org/ghc/docs/7.0-latest/html/libraries/base-4.3.1.0/System-IO-Unsafe.html) arise?

**Comment by mitchellwrosen** [comment]
I think this issue could be closed after we determine what to do about this one:

```haskell
-- | Return a 'Latch' that has a constant value
pureL :: a -> Latch a
pureL a = unsafePerformIO $ Ref.new $ Latch
    { _seenL  = beginning
    , _valueL = a
    , _evalL  = return a
    }
```

It seems to me that it would be fine for `pureL` to be inlined, but it might be better to add `NOINLINE` anyway.

**Comment by HeinrichApfelmus** [comment]
> It seems to me that it would be fine for pureL to be inlined, but it might be better to add NOINLINE anyway.

I agree.

Ideally, for reasons of efficiency, `pureL` would get its own constructor in `Latch`, but slapping `NOINLINE` on this and calling it a day sounds good to me.

**Comment by mitchellwrosen** [comment]
@HeinrichApfelmus Interesting, do you mean this?

```
data Latch a
  = PureL a
  | NotPureL {- what it is now -}
```

If so, I can make a new ticket to track that.

**Comment by HeinrichApfelmus** [comment]
> do you mean this?

Yes, indeed.

> If so, I can make a new ticket to track that.

Yes, please. That said, there are some performance issues with `Latch` that I need to think carefully about, and I'm not sure if the definition of `Latch` that you gave will survive. Then again, a constructor for `PureL` is highly likely.
