### ISSUE TITLE
Monoid instance for Event t (a -> a) ?

### ISSUE THREAD

**Issue by FabianBinz** [HeinrichApfelmus/reactive-banana#50]
The documentation states that there is `instance Monoid (Event t (a -> a))`, but you commented it out.

**Comment by mvcisback** [comment]
Is there a reason the Monoid Instance is still commented out?

**Comment by HeinrichApfelmus** [comment]
Well, I could not find a good reason to add it back in. The current semantics of `Event a` (as of reactive-banana-0.8) allows for multiple simultaneous events, so `accumE` can work with `union` or `unions` just fine.

However, I now lean towards disallowing simultaneous events. In this case, the monoid instance for `Event (a -> a)` would become much more important, and I would definitely add it back in.

**Comment by mvcisback** [comment]
@HeinrichApfelmus so its been awhile since I read Conal Elliott's paper, but isn't that issue circumvented via `unamb :: a -> a -> a`?

**Comment by HeinrichApfelmus** [comment]
That's a totally different story, I am afraid.

**Comment by HeinrichApfelmus** [comment]
The `unions` combinator currently serves as a substitute for a possible

    instance Monoid (Event (a -> a))

I would leave it at that for now. See #104 for more discussion on possible `Monoid` instances for `Event`.
