### ISSUE TITLE
Functor (AnyMoment Event)?

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#75]
We have this for `AnyMoment Behavior` - is there any reason we can't have it for `Event`?

**Comment by HeinrichApfelmus** [comment]
Should be fine. I think I was simply to lazy to implement it. The `Functor (AnyMoment Behavior)` instance made one particular example significantly nicer, that's why I had included it.

**Comment by HeinrichApfelmus** [comment]
I have added the desired instance.
