### ISSUE TITLE
reactive-banana doesn't satisfy the applicative-monad proposal

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#76]
The following is missing:

```haskell
 instance Functor (AnyMoment Identity) where
        fmap = liftM
        
instance Applicative (AnyMoment Identity) where
        pure = return
        (<*>) = ap
```

Apologies for not submitting a pull request - these lines are straight out of my personal NixOS configuration, where I just cat these lines into Switch.hs :)

**Comment by Twinside** [comment]
I've made a pull request after writing the exact same lines :)
