### ISSUE TITLE
'Identity' in reactive-banana collides with 'Identity' in base 

### ISSUE THREAD

**Issue by bennofs** [HeinrichApfelmus/reactive-banana#80]
The Identity functor from reactive-banana conflicts with the Identity as defined in http://hackage.haskell.org/package/base-4.8.0.0/docs/Data-Functor-Identity.html.

Can this type be renamed in reactive-banana? Identity is commonly used when working with transformers, too.

**Comment by HeinrichApfelmus** [comment]
Well, the `Identity` used here is essentially the `Identity` functor from `Data.Functor.Identity`, albeit with an additional phantom argument. I can't think of a better name right now, you will have to write

    import Reactive.Banana.Switch hiding (Identity)

for now.

**Comment by bennofs** [comment]
Ok thanks. Since this type is used where you would otherwise use a Behavior of Event maybe Constant (which also already exists but as far as I know not in base and it's also much less common since Const exists too) , Timeless or Ageless would be  good name?
(I'm not a native English speaker so I'm unsure if they really fit).

**Comment by HeinrichApfelmus** [comment]
This issue will likely be obsolete once the API moves to a monadic approach as planned in issue #97.

**Comment by HeinrichApfelmus** [comment]
The data type has been removed in the `monadic-api` branch.
