### ISSUE TITLE
Build failure due to PQueue package

### ISSUE THREAD

**Issue by FranklinChen** [HeinrichApfelmus/reactive-banana#87]
I suggest using https://github.com/hvr/multi-ghc-travis to test building with multiple versions of GHC and Cabal.

Right now, when I run `cabal install reactive-banana` on GHC 7.10.1, it fails because `pqueue` is failing:

```console
Data/PQueue/Internals.hs:64:19:
    Ambiguous occurrence ‘null’
    It could refer to either ‘Data.PQueue.Internals.null’,
                             defined at Data/PQueue/Internals.hs:161:1
                          or ‘Data.Foldable.null’,
                             imported from ‘Data.Foldable’ at Data/PQueue/Internals.hs:36:23-35
cabal: Error: some packages failed to install:
pqueue-1.2.1 failed during the building phase. The exception was:
ExitFailure 1
reactive-banana-0.8.1.1 depends on pqueue-1.2.1 which failed to install.
```

**Comment by FranklinChen** [comment]
Maybe switch to the maintained https://hackage.haskell.org/package/psqueues in any case?

**Comment by HeinrichApfelmus** [comment]
Thanks a lot for the suggestions! Being able to test multiple GHC versions with Travis is especially useful for me (and everyone else ;-)). I have updated the library to depend on `psqueues`.

**Comment by SelectricSimian** [comment]
This fix only seems to be available in `reactive-banana-0.8.1.2`, which doesn't seem to be available on `cabal`.  The latest version on cabal is `0.8.1.1.`.

**Comment by HeinrichApfelmus** [comment]
Thanks for the reminder! I have uploaded `reactive-banana-0.8.1.2` to hackage just now.

**Comment by HeinrichApfelmus** [comment]
The `pqueue` package has been updated to work with the current ecosystem, and I found it easer to depend on it again. This was done in commits f8157738cb01051550f6e17b05961163f68b6898 and b8d30cb8fd7b7d41f8576b424cf22ee07207d9e0
