### ISSUE TITLE
collect returns an empty list

### ISSUE THREAD

**Issue by gelisam** [HeinrichApfelmus/reactive-banana#95]
The [documentation](http://hackage.haskell.org/package/reactive-banana-0.8.1.2/docs/Reactive-Banana-Combinators.html#v:collect) for `collect` says that "the result will never contain an empty list." However, when I use `interact` to verify that `collect` doesn't spontaneously generate events of value `[]`, I see that it does generate such a spurious event:

    > interpret collect [[1,2,3],[]]
    [[[1,2,3]],[[]]]

I expected instead:

    > interpret collect [[1,2,3],[]]
    [[[1,2,3]],[]]

**Comment by HeinrichApfelmus** [comment]
Thanks for the report! I think this was simply a bug with `interpret`, which is now fixed. Please reopen this issue if the effect still occurs "in the wild"!
