### ISSUE TITLE
Consider deprecating either `valueB` or `initial`

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#96]
We have

```haskell
valueB :: Behavior t a -> Moment t a
valueB = M . Prim.initialB . unB

initial :: Behavior t a -> Moment t a
initial = M . Prim.initialB . unB
```

Having two functions with the same type in different namespaces suggests to me that these functions are *not* equivalent, however - they are actually identical! I think it would be simpler if we only exposed one of these functions to end users.

**Comment by HeinrichApfelmus** [comment]
Oh, I didn't notice that we have this twice. I think the `initial` combinator arose in the context of widget initialization, whereas `valueB` is a natural part of the dynamic event switching API.

**Comment by HeinrichApfelmus** [comment]
These two functions have been renamed to `valueB` and `valueBLater`.
