### ISSUE TITLE
Trick for getting a "better" `changes` event from a Behavior.

### ISSUE THREAD

**Issue by HeinrichApfelmus** [HeinrichApfelmus/reactive-banana#99]
Write down the following trick for obtaining an Event of (slightly delayed) changes from a Behavior in the documentations somewhere:

    plainChanges :: Frameworks t => Behavior t a -> Moment t (Event t a)
    plainChanges b = do
        (e, handle) <- newEvent
        eb <- changes b
        reactimate' $ fmap (fmap handle) eb
        return e

I don't really recommend this, because it doesn't give any guarantees of the time of occurrence in relation to other event occurrences in the networks, but sometimes it's useful to have.

**Comment by ocharles** [comment]
I agree it can be useful - I've written this entire code myself... though I can't quite remember why I needed it.
